### PR TITLE
UI/UX improvements

### LINKED ISSUE #129: Group list should have some padding for content
image

### LINKED ISSUE #164: [PE-D] Long names do not cause text wrap and they disappear into the side
### What is the issue:

Long names do not cause text to wrap. Names then disappear into the side.

### How to replicate:

1. Start with FriendDex with default data
2. Edit a friend to have a very long name (e.g AAAAAAAAAAAAAAAAAA x1000)
3. Observe that the text disappears into the side and the friend name is not visible.

### Expected behaviour
The text should wrap

### Why this is an issue:
Text should not flow off into the side without the ability to scroll and see.

### Screenshot

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: DrWala/ped#17

### LINKED ISSUE #202: [PE-D] Always returning back to the original list
Every time I add a meeting/date/debt into a person within a group, I will be redirected back to the original list. If there were hundreds of people in a group and I want to add $10 debt to everyone, it is going to be troublesome.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: chewwh09/ped#13

### PR DESCRIPTION
**Pull request by chesterhow**
- Retain current list of people when executing commands that shouldn't toggle the people displayed (Fixes #202)
  - i.e. `add-date`, `del-meeting`, `add-debt` should not reset the list of people back to the full list if they are currently viewing a certain group
  - Calling `updateFilteredPersonList` with no params will now check if there is a `currentGroup` to be displayed, and if so uses the appropriate predicate. Else it uses the predicate to show all persons.
- Add text wrap for long names (Fixes #164)
- Add padding to group names in group list panel (Fixes #129)

### CODE REVIEW

**Comment by ivantjh** [comment]
Should `AddCommand` always return to the all person view? Should `DeleteCommand` still stick to the groups view?

**Comment by chesterhow** [comment]
> Should `AddCommand` always return to the all person view?

Yes. As a user, after adding a new person, the natural intuition is to check that the new person has been added. While we have a confirmation message, it would be better to switch to the all persons view so that users can visually confirm that their new person has been added.

If they were still on the groups view, visual confirmation would not be possible as it takes another command to add the new person to the group.

> Should `DeleteCommand` still stick to the groups view?

Yes. Similarly, after deleting a person, the natural intuition would be to verify visually, by comparing the current list of people with the previous list of people they saw. If the person is no longer there, users can rest assured that the person is deleted.

If they were initially on the groups view, with 3 people. They would expect to see a new list of 2 people. Switching them to the all persons view would throw them off slightly as they are now presented with a list of potentially more people.

**Review by ivantjh — APPROVED** [review]
lgtm!

**Comment by ivantjh** [comment]
https://github.com/AY2021S2-CS2103T-W14-1/tp/pull/221#issuecomment-814739957 Ok thanks for the reply

**Pull request merged**
